version: '3'
services:
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  postgres:
    # get this from docker hub
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      # leave this folder (node_modules) as is
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker: 
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app

  